RELATED: ONE-4754 Add information about styling to the SDK documentation
gooddata/gooddata-ui pull request #371
Opened 2020-11-10 10:02 UTC by NestorEncinas

2020-11-10 10:03 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/549/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/325/ : SUCCESS in 5s

2020-11-10 13:00 UTC, ivan-nejezchleb requested changes

2020-11-10 13:00 UTC, ivan-nejezchleb commented on docs/10_vis__theme_provider.md
> +  kpiDashboards: {
1) lets use the same custom theme as in LiveExamples and Platform settings
2) kpiDashboards are now dashboards
3) dashboards section has now no meaning for UI SDK components, so I dont know whether to mention it here. It will change later with dashboardView component

2020-11-10 14:37 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/550/ : SUCCESS in 1m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/326/ : SUCCESS in 6s

2020-11-11 07:30 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/551/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/327/ : SUCCESS in 5s

2020-11-11 07:57 UTC, evgeniabogranskaya commented
Proofread, LGTM
The position of the new topic will be changed back to where it was initially as discussed with @NestorEncinas.

2020-11-11 08:43 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/552/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/328/ : SUCCESS in 4s

2020-11-11 08:45 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/553/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/329/ : SUCCESS in 4s

2020-11-11 08:47 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/554/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/330/ : SUCCESS in 4s

2020-11-11 11:46 UTC, ivan-nejezchleb commented on docs/10_vis__theme_provider.md
> +
I am missing here explanation, that in this case the theme will be loaded from workspace, where it needs to be correctly setup (may be link to the platform documentation how to set up theming on project?)

2020-11-11 12:11 UTC, NestorEncinas commented on docs/10_vis__theme_provider.md
> +
Might need to wait until platform documentation has the `Theming` added?

2020-11-11 13:32 UTC, evgeniabogranskaya commented on docs/10_vis__theme_provider.md
> +
I checked with Vendi, info about themes will be ready in the online help in R219.

2020-11-11 15:47 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/558/ : SUCCESS in 1m 03s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/334/ : SUCCESS in 6s

2020-11-11 15:54 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/559/ : SUCCESS in 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/335/ : SUCCESS in 4s

2020-11-11 15:56 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/560/ : SUCCESS in 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/336/ : SUCCESS in 4s

2020-11-11 15:57 UTC, ivan-nejezchleb approved these changes

2020-11-12 09:39 UTC, merged

2020-11-12 09:40 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/562/ : SUCCESS in 45s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul-el7/67/ : FAILURE in 2m 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/160/ : SUCCESS in 15s