RELATED: RAIL-4600 Update dashboard component doc
gooddata/gooddata-ui pull request #585
Opened 2023-02-28 13:12 UTC by ivanmjartan

2023-02-28 13:13 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1246/ : SUCCESS in 1m 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/839/ : SUCCESS in 10s

2023-02-28 15:00 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1247/ : SUCCESS in 1m 04s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/840/ : SUCCESS in 5s

2023-02-28 15:41 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1248/ : SUCCESS in 1m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/841/ : SUCCESS in 6s

2023-02-28 15:53 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1249/ : SUCCESS in 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/842/ : SUCCESS in 4s

2023-03-01 09:00 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1252/ : SUCCESS in 1m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/844/ : SUCCESS in 4s

2023-03-01 09:29 UTC, kandl commented on docs/18_dashboard_component.md
> +                initialRenderMode:"edit",
We have this prop currently set as `@internal`, should we make it public?

2023-03-01 09:29 UTC, kandl commented on docs/18_dashboard_intro.md
> +It provide APIs to allow customization to expand the eventing and interactivity.
I would also mention that some parts are still in beta stage so users should use them carefully

2023-03-01 09:29 UTC, kandl commented on docs/18_dashboard_intro.md
> +for example integration of [Analytical Designer](https://help.gooddata.com/pages/viewpage.action?pageId=86794494) component to create new insights.
This is a bit changing the meaning of the previous part which is probably more correct?
It can probably confuse users as integration of the Analytical Designer is not possible in the easy way with plain Dashboard component.

2023-03-01 09:29 UTC, kandl commented on docs/18_dashboard_intro.md
> +- Dashboard component does not provide creation and edit of insights
I would probably also mention that this is currently possible only in the platform / cloud.

2023-03-01 09:29 UTC, kandl commented on docs/18_dashboard_intro.md
> +- Dashboard component does not provide creation and edit of insights
Should we also mention drill limitations? (That you need to handle some of the drill types by yourself?)

2023-03-01 09:40 UTC, ivanmjartan commented on docs/18_dashboard_component.md
> +                initialRenderMode:"edit",
I guess yes ... so I will prepare PR to RC for this change.

2023-03-01 09:44 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +It provide APIs to allow customization to expand the eventing and interactivity.
I will not add this warning here ... this warning is everywhere around ... big yellow square ... I have count like 5 warnings around and I will let this as it is ...

2023-03-01 09:47 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +for example integration of [Analytical Designer](https://help.gooddata.com/pages/viewpage.action?pageId=86794494) component to create new insights.
Pls I do not get it ... my idea was that some feature in KD are base on customisations ... 

So if this sounds like problem for u  will change it just to 

`All mentioned components are based on Dashboard component with additional customisations. `

No other examples

2023-03-01 10:14 UTC, kandl commented on docs/18_dashboard_intro.md
> +It provide APIs to allow customization to expand the eventing and interactivity.
I woud really not switch from `is at an early stage of its lifecycle` to `"is stable"` as it is not true :)

2023-03-01 10:24 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +It provide APIs to allow customization to expand the eventing and interactivity.
Added

2023-03-01 10:25 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +for example integration of [Analytical Designer](https://help.gooddata.com/pages/viewpage.action?pageId=86794494) component to create new insights.
removed

2023-03-01 10:45 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1253/ : SUCCESS in 1m 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/845/ : SUCCESS in 4s

2023-03-02 08:12 UTC, Mara3l requested changes

2023-03-02 08:12 UTC, Mara3l commented on docs/18_dashboard_intro.md
> +Dashboard component provide end-to-and solution for creation and consumption of dashboards with full drag-and-drop editing experience.
Typo:
Dashboard component provides >end-to-end< solution for ...

2023-03-02 08:12 UTC, Mara3l commented on docs/18_dashboard_intro.md
> +   all view components used on a dashboard, and integration with the eventing. It also support creation of new dashboard and also editing existing dashboard via full drag-and-drop editing experience.
I would reword this:
It also supports a full drag-and-drop experience for creating and editing existing dashboards.

2023-03-02 08:12 UTC, Mara3l commented on docs/18_dashboard_intro.md
> +- Dashboard component does not provide handling of some drill types, like Drill to URL or Drill to Dashboard see [example](https://gdui-examples.herokuapp.com/dashboard/drill-to-dashboard) how to han
Rephrasing:
... of some drill types; for example, Drill to URL or Drill to Dashboard. Here is an [example](https://gdui-examples.herokuapp.com/dashboard/drill-to-dashboard) how to handle these drill types.

2023-03-02 12:32 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +Currently, the Dashboard component is at an early stage of its lifecycle, some parts are still in beta stage so users should use them carefully.
Fixed

2023-03-02 12:33 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +Dashboard component provide end-to-and solution for creation and consumption of dashboards with full drag-and-drop editing experience.
fixed

2023-03-02 12:35 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +   all view components used on a dashboard, and integration with the eventing. It also support creation of new dashboard and also editing existing dashboard via full drag-and-drop editing experience.
fixed

2023-03-02 12:37 UTC, ivanmjartan commented on docs/18_dashboard_intro.md
> +- Dashboard component does not provide handling of some drill types, like Drill to URL or Drill to Dashboard see [example](https://gdui-examples.herokuapp.com/dashboard/drill-to-dashboard) how to han
fixed

2023-03-02 12:40 UTC, gdgate commented
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1254/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-oss-check/846/ : SUCCESS in 6s

2023-03-02 13:17 UTC, kandl approved these changes
LGTM

2023-03-02 13:18 UTC, yenkins commented
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-gate-PR585

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

2023-03-02 13:20 UTC, merged

2023-03-02 13:20 UTC, gdgate commented
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/client-libs/job/gooddata-ui-documentation-validation/1255/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sonarqube-scan-zuul-gate/177/ : SUCCESS in 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-merge-compliance-check/372/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-fossa-scanning-zuul/14/ : SUCCESS in 2m 00s (non-voting)